package com.cramsan.agentic.core

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Application configuration - controls system settings like pool size,
 * timeouts, and provider configurations.
 */
@Serializable
data class AgenticConfig(
    val agentPoolSize: Int,
    val defaultTaskTimeoutSeconds: Long = 3600L,
    val baseBranch: String,
    val docsDir: String,
    val aiProvider: AiProviderConfig = AiProviderConfig.ClaudeCli(),
    val vcsProvider: VcsProviderConfig,
    val taskListProvider: TaskListProviderConfig = TaskListProviderConfig.Document(),
)

@Serializable
sealed class AiProviderConfig {
    abstract val model: String

    @Serializable
    @SerialName("claude-api")
    data class ClaudeApi(
        override val model: String = "claude-opus-4-6",
        val anthropicApiKeyEnvVar: String = "ANTHROPIC_API_KEY",
    ) : AiProviderConfig()

    @Serializable
    @SerialName("claude-cli")
    data class ClaudeCli(
        override val model: String = "claude-opus-4-6",
        val cliPath: String = "claude",
        /**
         * When true, the CLI is invoked with --dangerously-skip-permissions and
         * --output-format json, allowing full autonomous agent execution.
         * Suitable for 'run start'. When false (default), tool use is not
         * supported and the provider is restricted to validation/review workloads.
         */
        val fullAccess: Boolean = false,
    ) : AiProviderConfig()

    @Serializable
    @SerialName("fake")
    data class Fake(
        override val model: String = "fake-model",
        val mode: FakeMode = FakeMode.TEST,
        val delayMs: Long = 0L,
        val autoCompleteAfterTurns: Int = 5,
        val defaultTextResponse: String = "I understand. Let me continue working on this task.",
    ) : AiProviderConfig()
}

@Serializable
enum class FakeMode {
    @SerialName("test")
    TEST,
    @SerialName("demo")
    DEMO,
}

@Serializable
sealed class VcsProviderConfig {
    @Serializable
    @SerialName("github")
    data class GitHub(val owner: String, val repo: String) : VcsProviderConfig()

    @Serializable
    @SerialName("local")
    data class Local(
        val stateFile: String = ".agentic/local_prs.json",
        val autoMerge: Boolean = false,
    ) : VcsProviderConfig()
}

@Serializable
sealed class TaskListProviderConfig {
    /**
     * Reads tasks from a markdown document (such as one generated by the workflow)
     * and persists each task as a JSON file under [tasksOutputDir].
     *
     * @property documentPath Path to the source markdown document, relative to agenticDir.
     * @property tasksOutputDir Directory for persisted task JSON files, relative to agenticDir.
     */
    @Serializable
    @SerialName("document")
    data class Document(
        val documentPath: String = "docs/task-list.md",
        val tasksOutputDir: String = "tasks/",
    ) : TaskListProviderConfig()

    /**
     * Uses an in-memory fake implementation. For testing only.
     */
    @Serializable
    @SerialName("fake")
    data object Fake : TaskListProviderConfig()
}
