package com.cramsan.agentic.core

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.nio.file.Path

/**
 * The high-level lifecycle position of the planning workflow, returned by
 * [com.cramsan.agentic.input.WorkflowService.getState]. The workflow advances linearly through
 * stages; a stage must be approved before the next can start.
 */
@Serializable
sealed class WorkflowStatus {
    /** No stage has been started yet. */
    @Serializable
    @SerialName("not_started")
    data object NotStarted : WorkflowStatus()

    /** A stage is currently being generated by the AI. */
    @Serializable
    @SerialName("stage_in_progress")
    data class StageInProgress(val stageId: String) : WorkflowStatus()

    /** Generation is complete; the stage output is awaiting human approval. */
    @Serializable
    @SerialName("stage_pending_approval")
    data class StagePendingApproval(val stageId: String) : WorkflowStatus()

    /**
     * All stages have been approved. The task list is ready and `agentic run start`
     * can begin autonomous execution.
     */
    @Serializable
    @SerialName("complete")
    data object Complete : WorkflowStatus()
}

/**
 * Emitted when an input document is modified after a stage was approved. The presence
 * of warnings does not block workflow progression, but indicates the approved output
 * may no longer reflect the current inputs.
 */
data class StageApprovalWarning(
    val stageId: String,
    val stageName: String,
    val changedInputs: List<String>,
)

/**
 * Snapshot of the entire workflow's current state, returned by
 * [com.cramsan.agentic.input.WorkflowService.getState]. Callers use this to decide which
 * CLI commands to offer the user (start, revise, approve).
 */
data class WorkflowState(
    val status: WorkflowStatus,
    val completedStages: List<String>,
    val currentStage: WorkflowStageConfig?,
    val nextStage: WorkflowStageConfig?,
    val approvalWarnings: List<StageApprovalWarning> = emptyList(),
)

/** The output document produced by a workflow stage, returned from [com.cramsan.agentic.input.WorkflowService.startStage]. */
data class StageDocument(
    val stageId: String,
    val stageName: String,
    val path: Path,
)

/** A configuration-level error detected during [com.cramsan.agentic.input.WorkflowService.validateWorkflowConfig]. */
data class WorkflowConfigError(
    val type: WorkflowConfigErrorType,
    val message: String,
    val stageId: String? = null,
)

/** Categories of structural errors that can appear in a [com.cramsan.agentic.core.WorkflowConfig]. */
enum class WorkflowConfigErrorType {
    CIRCULAR_DEPENDENCY,
    MISSING_DEPENDENCY,
    DUPLICATE_STAGE_ID,
    INVALID_OUTPUT_FILE,
}
