@file:Suppress("MagicNumber")

package com.cramsan.flyerboard.client.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2E02E9)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4A3AFF)
val onPrimaryContainerLight = Color(0xFFDAD7FF)
val secondaryLight = Color(0xFFB90538)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDC2C4F)
val onSecondaryContainerLight = Color(0xFFFFFBFF)
val tertiaryLight = Color(0xFF416900)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF84CC16)
val onTertiaryContainerLight = Color(0xFF315200)
val errorLight = Color(0xFFBB0011)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFEA0018)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1A25)
val surfaceLight = Color(0xFFFCF8FA)
val onSurfaceLight = Color(0xFF1B1B1D)
val surfaceVariantLight = Color(0xFFE3E0F6)
val onSurfaceVariantLight = Color(0xFF464557)
val outlineLight = Color(0xFF777588)
val outlineVariantLight = Color(0xFFC7C4DA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303031)
val inverseOnSurfaceLight = Color(0xFFF3F0F1)
val inversePrimaryLight = Color(0xFFC3C0FF)
val surfaceDimLight = Color(0xFFDCD9DB)
val surfaceBrightLight = Color(0xFFFCF8FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F4)
val surfaceContainerLight = Color(0xFFF0EDEE)
val surfaceContainerHighLight = Color(0xFFEAE7E9)
val surfaceContainerHighestLight = Color(0xFFE5E2E3)

val primaryLightMediumContrast = Color(0xFF2100B6)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF4A3AFF)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF72001F)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFFD12348)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF233D00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4B7900)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDC0016)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFCF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1B1A25)
val surfaceLightMediumContrast = Color(0xFFFCF8FA)
val onSurfaceLightMediumContrast = Color(0xFF111112)
val surfaceVariantLightMediumContrast = Color(0xFFE3E0F6)
val onSurfaceVariantLightMediumContrast = Color(0xFF353445)
val outlineLightMediumContrast = Color(0xFF525163)
val outlineVariantLightMediumContrast = Color(0xFF6D6B7E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303031)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F0F1)
val inversePrimaryLightMediumContrast = Color(0xFFC3C0FF)
val surfaceDimLightMediumContrast = Color(0xFFC8C6C7)
val surfaceBrightLightMediumContrast = Color(0xFFFCF8FA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F3F4)
val surfaceContainerLightMediumContrast = Color(0xFFEAE7E9)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDCDD)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D1D2)

val primaryLightHighContrast = Color(0xFF1A0099)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF2F06EA)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF5F0018)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF96002B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1C3200)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF315200)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000B)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFCF8FF)
val onBackgroundLightHighContrast = Color(0xFF1B1A25)
val surfaceLightHighContrast = Color(0xFFFCF8FA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE3E0F6)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2B2A3B)
val outlineVariantLightHighContrast = Color(0xFF484759)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303031)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC3C0FF)
val surfaceDimLightHighContrast = Color(0xFFBAB8B9)
val surfaceBrightLightHighContrast = Color(0xFFFCF8FA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3F0F1)
val surfaceContainerLightHighContrast = Color(0xFFE5E2E3)
val surfaceContainerHighLightHighContrast = Color(0xFFD6D4D5)
val surfaceContainerHighestLightHighContrast = Color(0xFFC8C6C7)

val primaryDark = Color(0xFFC3C0FF)
val onPrimaryDark = Color(0xFF1D00A5)
val primaryContainerDark = Color(0xFF4A3AFF)
val onPrimaryContainerDark = Color(0xFFDAD7FF)
val secondaryDark = Color(0xFFFFB2B7)
val onSecondaryDark = Color(0xFF67001B)
val secondaryContainerDark = Color(0xFFFF516A)
val onSecondaryContainerDark = Color(0xFF45000F)
val tertiaryDark = Color(0xFF9EE939)
val onTertiaryDark = Color(0xFF1F3700)
val tertiaryContainerDark = Color(0xFF84CC16)
val onTertiaryContainerDark = Color(0xFF315200)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFFFF5449)
val onErrorContainerDark = Color(0xFF340001)
val backgroundDark = Color(0xFF13121D)
val onBackgroundDark = Color(0xFFE4E0F0)
val surfaceDark = Color(0xFF131314)
val onSurfaceDark = Color(0xFFE5E2E3)
val surfaceVariantDark = Color(0xFF464557)
val onSurfaceVariantDark = Color(0xFFC7C4DA)
val outlineDark = Color(0xFF918FA3)
val outlineVariantDark = Color(0xFF464557)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E3)
val inverseOnSurfaceDark = Color(0xFF303031)
val inversePrimaryDark = Color(0xFF4837FD)
val surfaceDimDark = Color(0xFF131314)
val surfaceBrightDark = Color(0xFF39393A)
val surfaceContainerLowestDark = Color(0xFF0E0E0F)
val surfaceContainerLowDark = Color(0xFF1B1B1D)
val surfaceContainerDark = Color(0xFF1F1F21)
val surfaceContainerHighDark = Color(0xFF2A2A2B)
val surfaceContainerHighestDark = Color(0xFF353436)

val primaryDarkMediumContrast = Color(0xFFDBD8FF)
val onPrimaryDarkMediumContrast = Color(0xFF160086)
val primaryContainerDarkMediumContrast = Color(0xFF8582FF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFD1D3)
val onSecondaryDarkMediumContrast = Color(0xFF530014)
val secondaryContainerDarkMediumContrast = Color(0xFFFF516A)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFA6F141)
val onTertiaryDarkMediumContrast = Color(0xFF172B00)
val tertiaryContainerDarkMediumContrast = Color(0xFF84CC16)
val onTertiaryContainerDarkMediumContrast = Color(0xFF1C3200)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF13121D)
val onBackgroundDarkMediumContrast = Color(0xFFE4E0F0)
val surfaceDarkMediumContrast = Color(0xFF131314)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF464557)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDDDAF0)
val outlineDarkMediumContrast = Color(0xFFB2B0C5)
val outlineVariantDarkMediumContrast = Color(0xFF908EA2)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E2E3)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2B)
val inversePrimaryDarkMediumContrast = Color(0xFF2E00E9)
val surfaceDimDarkMediumContrast = Color(0xFF131314)
val surfaceBrightDarkMediumContrast = Color(0xFF454445)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070708)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D1F)
val surfaceContainerDarkMediumContrast = Color(0xFF282829)
val surfaceContainerHighDarkMediumContrast = Color(0xFF333234)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3D3F)

val primaryDarkHighContrast = Color(0xFFF1EEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBEBCFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF05003A)
val secondaryDarkHighContrast = Color(0xFFFFECEB)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFADB2)
val onSecondaryContainerDarkHighContrast = Color(0xFF210004)
val tertiaryDarkHighContrast = Color(0xFFD0FF93)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF8ED725)
val onTertiaryContainerDarkHighContrast = Color(0xFF050E00)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA5)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF13121D)
val onBackgroundDarkHighContrast = Color(0xFFE4E0F0)
val surfaceDarkHighContrast = Color(0xFF131314)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF464557)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF1EEFF)
val outlineVariantDarkHighContrast = Color(0xFFC3C0D6)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2E00E9)
val surfaceDimDarkHighContrast = Color(0xFF131314)
val surfaceBrightDarkHighContrast = Color(0xFF505051)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F21)
val surfaceContainerDarkHighContrast = Color(0xFF303031)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474648)

public val lightScheme =
    lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

public val darkScheme =
    darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

public val mediumContrastLightColorScheme =
    lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

public val highContrastLightColorScheme =
    lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

public val mediumContrastDarkColorScheme =
    darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

public val highContrastDarkColorScheme =
    darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
