package com.cramsan.agentic.coordination

import com.cramsan.agentic.core.Task
import com.cramsan.framework.logging.logI
import com.cramsan.framework.logging.logW
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.nio.file.Files
import java.nio.file.Path

private const val TAG = "DocumentTaskListProvider"
        private const val TASK_FILE_NAME = "task.json"

/**
 * A [TaskListProvider] that reads task definitions from a markdown document
 * (such as the one generated by the workflow's task-list stage) and persists
 * each task as an individual JSON file under [tasksDir].
 *
 * On the first call to [provide], tasks are parsed from [documentPath] and
 * written to [tasksDir]/{taskId}/task.json. On subsequent calls, tasks are
 * read back from those JSON files (the source document is not re-parsed).
 *
 * Supports both plain and bold-markdown field prefixes:
 *   - `Title: ...` and `**Title:** ...`
 *   - `Description: ...` and `**Description:** ...`
 *   - `Dependencies: ...` and `**Dependencies:** ...`
 *   - `Timeout: ...` and `**Timeout:** ...` (optional)
 */
class DocumentTaskListProvider(
    private val documentPath: Path,
    private val tasksDir: Path,
    private val json: Json,
) : TaskListProvider {

    override suspend fun provide(): List<Task> {
        return if (isInitialized()) {
            logI(TAG, "Task files already exist in $tasksDir — loading from persisted files")
            loadFromTaskFiles()
        } else {
            logI(TAG, "No task files found — parsing document at $documentPath")
            val tasks = parseDocument()
            writeTaskFiles(tasks)
            logI(TAG, "Provisioned ${tasks.size} task files under $tasksDir")
            tasks
        }
    }

    override fun isInitialized(): Boolean {
        if (!Files.exists(tasksDir)) return false
        return Files.list(tasksDir).use { stream ->
            stream.anyMatch { dir ->
                Files.isDirectory(dir) && Files.exists(dir.resolve(TASK_FILE_NAME))
            }
        }
    }

    private fun parseDocument(): List<Task> {
        require(Files.exists(documentPath)) {
            "Task list document not found at $documentPath"
        }
        val content = Files.readString(documentPath)
        val parsedTasks = mutableListOf<Task>()

        // Matches both plain and bold-markdown field prefixes:
        //   Title: ...  or  **Title:** ...
        val taskPattern = Regex(
            """## Task:\s*(\S+)\s*\n""" +
            """\*{0,2}Title:\*{0,2}\s*(.+)\n""" +
            """\*{0,2}Description:\*{0,2}\s*(.+)\n""" +
            """\*{0,2}Dependencies:\*{0,2}\s*(.+?)""" +
            """(?:\n\*{0,2}Timeout:\*{0,2}\s*(\d+))?""" +
            """(?:\n|\z)""",
            setOf(RegexOption.MULTILINE),
        )

        for (match in taskPattern.findAll(content)) {
            val id = match.groupValues[1].trim()
            val title = match.groupValues[2].trim()
            val description = match.groupValues[3].trim()
            val depsRaw = match.groupValues[4].trim()
            val timeout = match.groupValues[5].trim().toLongOrNull() ?: 3600L

            val dependencies = if (depsRaw.equals("none", ignoreCase = true) || depsRaw.isBlank()) {
                emptyList()
            } else {
                depsRaw.split(",").map { it.trim() }.filter { it.isNotEmpty() }
            }

            parsedTasks.add(
                Task(
                    id = id,
                    title = title,
                    description = description,
                    dependencies = dependencies,
                    timeoutSeconds = timeout,
                )
            )
        }

        if (parsedTasks.isEmpty()) {
            throw IllegalStateException("No tasks found in task list document at $documentPath")
        }

        logI(TAG, "Parsed ${parsedTasks.size} tasks from $documentPath")
        return parsedTasks
    }

    private fun writeTaskFiles(tasks: List<Task>) {
        Files.createDirectories(tasksDir)
        for (task in tasks) {
            val taskDir = tasksDir.resolve(task.id)
            Files.createDirectories(taskDir)
            val taskFile = taskDir.resolve(TASK_FILE_NAME)
            Files.writeString(taskFile, json.encodeToString(task))
        }
    }

    private fun loadFromTaskFiles(): List<Task> {
        return Files.list(tasksDir).use { stream ->
            stream
                .filter { Files.isDirectory(it) }
                .map { dir -> dir.resolve(TASK_FILE_NAME) }
                .filter { Files.exists(it) }
                .map { taskFile ->
                    try {
                        json.decodeFromString<Task>(Files.readString(taskFile))
                    } catch (e: Exception) {
                        logW(TAG, "Failed to read task file $taskFile: ${e.message}")
                        null
                    }
                }
                .filter { it != null }
                .map { it!! }
                .toList()
        }
    }
}
