# image-name                dockerfile
edifikana-backend           edifikana/back-end/Dockerfile
edifikana-frontend          edifikana/front-end/app-wasm/Dockerfile
runasimi-frontend           runasimi/front-end/app-wasm/Dockerfile
samples-ktor-service        samples/service-ktor/Dockerfile
samples-wasm-frontend       samples/jbcompose-wasm-app/Dockerfile
