package com.cramsan.edifikana.server.datastore.supabase.models

import com.cramsan.edifikana.lib.model.commonArea.CommonAreaId
import com.cramsan.edifikana.lib.model.commonArea.CommonAreaType
import com.cramsan.edifikana.lib.model.property.PropertyId
import com.cramsan.framework.annotations.DatabaseModel
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * Entity representing a common area row in the `common_areas` Supabase table.
 */
@OptIn(ExperimentalTime::class)
@Serializable
@DatabaseModel
data class CommonAreaEntity(
    @SerialName("common_area_id")
    val commonAreaId: CommonAreaId,
    @SerialName("property_id")
    val propertyId: PropertyId,
    val name: String,
    val type: CommonAreaType,
    val description: String? = null,
    @SerialName("created_at")
    val createdAt: Instant,
    @SerialName("deleted_at")
    val deletedAt: Instant? = null,
) {
    companion object {
        const val COLLECTION = "common_areas"
    }

    /**
     * Entity used when inserting a new common area (no ID or timestamps — generated by DB).
     */
    @Serializable
    @DatabaseModel
    data class CreateCommonAreaEntity(
        @SerialName("property_id")
        val propertyId: PropertyId,
        val name: String,
        val type: CommonAreaType,
        val description: String? = null,
    )
}
