package com.cramsan.edifikana.server.datastore.supabase.models

import com.cramsan.edifikana.lib.model.CommonAreaId
import com.cramsan.edifikana.lib.model.CommonAreaType
import com.cramsan.edifikana.lib.model.OrganizationId
import com.cramsan.edifikana.lib.model.PropertyId
import com.cramsan.edifikana.server.service.models.CommonArea
import com.cramsan.framework.annotations.SupabaseModel
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * Entity representing a common area row in the `common_areas` Supabase table.
 */
@OptIn(ExperimentalTime::class)
@Serializable
@SupabaseModel
data class CommonAreaEntity(
    @SerialName("common_area_id")
    val commonAreaId: String,
    @SerialName("property_id")
    val propertyId: PropertyId,
    @SerialName("org_id")
    val orgId: OrganizationId,
    val name: String,
    val type: String,
    val description: String? = null,
    @SerialName("created_at")
    val createdAt: Instant,
    @SerialName("deleted_at")
    val deletedAt: Instant? = null,
) {
    companion object {
        const val COLLECTION = "common_areas"
    }

    /**
     * Entity used when inserting a new common area (no ID or timestamps — generated by DB).
     */
    @Serializable
    @SupabaseModel
    data class CreateCommonAreaEntity(
        @SerialName("property_id")
        val propertyId: PropertyId,
        @SerialName("org_id")
        val orgId: OrganizationId,
        val name: String,
        val type: String,
        val description: String? = null,
    )
}

/**
 * Maps a [CommonAreaEntity] to the [CommonArea] domain model.
 */
@OptIn(ExperimentalTime::class)
fun CommonAreaEntity.toCommonArea() = CommonArea(
    id = CommonAreaId(commonAreaId),
    propertyId = propertyId,
    orgId = orgId,
    name = name,
    type = CommonAreaType.fromString(type),
    description = description,
    createdAt = createdAt,
)
