package com.cramsan.flyerboard.server.controller

import com.cramsan.flyerboard.lib.model.network.FlyerListNetworkResponse
import com.cramsan.flyerboard.lib.model.network.FlyerNetworkResponse
import com.cramsan.flyerboard.server.service.models.Flyer
import com.cramsan.flyerboard.server.service.models.PaginatedList
import com.cramsan.framework.annotations.NetworkModel

/**
 * Maps a [Flyer] domain model to a [FlyerNetworkResponse].
 *
 * [Instant] timestamps are serialised as ISO-8601 strings. [fileUrl] is the short-lived signed
 * URL generated by [FlyerService]; it may be null when the storage call failed.
 */
@NetworkModel
fun Flyer.toFlyerNetworkResponse(): FlyerNetworkResponse = FlyerNetworkResponse(
    id = id,
    title = title,
    description = description,
    fileUrl = fileUrl,
    status = status,
    expiresAt = expiresAt?.toString(),
    uploaderId = uploaderId,
    createdAt = createdAt.toString(),
    updatedAt = updatedAt.toString(),
)

/**
 * Maps a paginated [Flyer] list to a [FlyerListNetworkResponse].
 */
@NetworkModel
fun PaginatedList<Flyer>.toFlyerListNetworkResponse(): FlyerListNetworkResponse = FlyerListNetworkResponse(
    flyers = items.map { it.toFlyerNetworkResponse() },
    total = total,
    offset = offset,
    limit = limit,
)
