package com.cramsan.agentic.ai

import kotlinx.serialization.json.JsonObject

/**
 * A single turn in a conversation with the AI. [role] is either `"user"` or `"assistant"`.
 * Multi-turn context is accumulated by [com.cramsan.agentic.claude.DefaultAgentSession] and passed
 * as a growing [List] of messages on each [AiProvider.chat] call.
 */
data class AiMessage(val role: String, val content: String)

/**
 * A tool that the AI may invoke. The [inputSchema] is a JSON Schema object describing the
 * expected parameters. Tools are defined statically in `claude/AgentTools.kt` and passed on
 * every agent turn so the model knows what capabilities are available.
 */
data class AiTool(val name: String, val description: String, val inputSchema: JsonObject)

/**
 * A single block within an [AiResponse]. Claude may interleave [Text] and [ToolCall] blocks;
 * [com.cramsan.agentic.claude.DefaultAgentSession] processes all blocks before deciding whether
 * to loop or terminate.
 */
sealed class AiContentBlock {
    /** Plain text generated by the model. Typically the final response or reasoning commentary. */
    data class Text(val text: String) : AiContentBlock()

    /**
     * A request from the model to invoke a registered tool. The agent session dispatches the
     * call, collects the result, and appends both the call and result to the message history
     * before the next turn.
     */
    data class ToolCall(val id: String, val name: String, val input: JsonObject) : AiContentBlock()
}

/**
 * The model's response for one [AiProvider.chat] call. A response may contain multiple content
 * blocks; [stopReason] indicates why generation stopped (`"end_turn"`, `"tool_use"`, etc.).
 */
data class AiResponse(
    val id: String,
    val content: List<AiContentBlock>,
    val stopReason: String?,
)

/**
 * Thrown by [AiProvider] implementations when the underlying API or CLI call fails non-transiently.
 * [exitCode] carries the HTTP status code (for API providers) or process exit code (for CLI providers);
 * `-1` is used when no exit code is available.
 *
 * [com.cramsan.agentic.ai.RetryingAiProvider] re-throws this exception immediately for all errors
 * except those that match known rate-limit/usage-limit keywords.
 */
class AiProviderException(message: String, val exitCode: Int = -1) : Exception(message)

/**
 * Provider-agnostic interface for sending conversational turns to an AI model.
 *
 * Implementations include:
 * - [com.cramsan.agentic.ai.claude.ClaudeAiProvider]: direct Anthropic HTTP API
 * - [com.cramsan.agentic.ai.claude.ClaudeCliAiProvider]: delegates to the `claude` CLI binary
 * - [com.cramsan.agentic.ai.RetryingAiProvider]: decorator that retries on rate-limit errors
 * - [com.cramsan.agentic.ai.fake.FakeAiProvider]: in-memory stub for tests and demos
 *
 * [chat] is the only operation; stateless multi-turn context is passed by the caller via [messages].
 * Callers are responsible for accumulating the conversation history — this interface has no memory.
 */
interface AiProvider {
    /**
     * Sends [messages] (including all prior turns) to the model under [systemPrompt] with the
     * given [tools] available. Returns the model's next response, which may contain text, tool
     * calls, or both.
     *
     * Throws [AiProviderException] on non-retryable failures. Rate-limit errors are typically
     * handled by [com.cramsan.agentic.ai.RetryingAiProvider] before reaching the caller.
     */
    suspend fun chat(
        systemPrompt: String,
        messages: List<AiMessage>,
        tools: List<AiTool>,
    ): AiResponse
}
