# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build All Targets

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  ANDROID_HOME: "/opt/Android/sdk"
  
jobs:
  build:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # Skip if commit message contains [skip ci]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
    - name: Make changes
      run: |
        echo "// auto-generated" >> README.md
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "[skip ci] Committing CI changes" || echo "No changes to commit"
        git push