# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build All Targets Pull Request

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, ready_for_review, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  ANDROID_HOME: "/opt/Android/sdk"
  
jobs:
  build:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[ignore-commit]') && !github.event.pull_request.draft" # Skip if commit message contains keyword or PR is draft
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: releaseAll

  snapshots:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[ignore-commit]') && !github.event.pull_request.draft" # Skip if commit message contains keyword or PR is draft
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Clear All Snapshots
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clearRoborazziDebug
      - name: Record New Snapshots(Android-Debug)
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: recordRoborazziDebug
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[ignore-commit] Committing CI changes" || echo "No changes to commit"
          git push
