# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build All Targets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  ANDROID_HOME: "/opt/Android/sdk"
  
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        GOOGLE_SERVICES_PREPROD: ${{ secrets.GOOGLE_SERVICES_PREPROD }}
        GOOGLE_SERVICES_PROD: ${{ secrets.GOOGLE_SERVICES_PROD }}
      run: |
        echo "Prod Encoded"
        echo "$GOOGLE_SERVICES_PREPROD"
        echo "PreProd Encoded"
        echo "$GOOGLE_SERVICES_PROD"
        echo "$GOOGLE_SERVICES_PREPROD" | base64 -d > edifikana/front-end/app-android/src/preprod/google-services.json
        echo "$GOOGLE_SERVICES_PROD" | base64 -d > edifikana/front-end/app-android/src/prod/google-services.json
        echo "Prod Decoded"
        cat edifikana/front-end/app-android/src/preprod/google-services.json
        echo "PreProd Decoded"
        cat edifikana/front-end/app-android/src/prod/google-services.json
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: releaseAll
