name: Create Release Tag on Main Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create and push tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin master
        git checkout master
        TAG=$(date -u +%Y%m%d_%H%M%S)
        git tag $TAG
        git push origin $TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}