name: Create Release Tag on Main Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "CI"
    steps:
    - uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_PAT }}
    - name: Create and push tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin main
        git checkout main
        TAG=$(date -u +%Y%m%d_%H%M%S)
        git tag -a $TAG -m "Release tag created on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        git push origin $TAG