# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will deploy the changes to a given stage. Changes
# will be validated by running the build and tests.

name: Deploy Supabase Step

on:
  workflow_call:
    secrets:
      supabase_access_token:
        required: true
      supabase_project_id:
        required: true

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    - run: supabase db push --project-ref $PROJECT_ID