# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish Edifikana

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  ANDROID_HOME: "/opt/Android/sdk"

jobs:
  build-android-staging:
    runs-on: self-hosted
    needs: build-function-staging
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        GOOGLE_SERVICES_PREPROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PREPROD }}
        GOOGLE_SERVICES_PROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PROD }}
      run: |
        echo "$GOOGLE_SERVICES_PREPROD" | base64 -d > edifikana/front-end/app-android/src/preprod/google-services.json
        echo "$GOOGLE_SERVICES_PROD" | base64 -d > edifikana/front-end/app-android/src/prod/google-services.json
    - name: Load Android upload signing key
      env:
        UPLOAD_KEY: ${{ secrets.EDIFIKANA_UPLOAD_KEY }}
      run: echo "$UPLOAD_KEY" | base64 -d > edifikana/front-end/app-android/.secrets/upload.jks
    - name: Build Bundle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      env:
        EDIFIKANA_STORE_PASSWORD: ${{ secrets.EDIFIKANA_STORE_PASSWORD }}
        EDIFIKANA_KEY_ALIAS: ${{ secrets.EDIFIKANA_KEY_ALIAS }}
        EDIFIKANA_KEY_PASSWORD: ${{ secrets.EDIFIKANA_KEY_PASSWORD }}
      with:
        arguments: :edifikana:front-end:app-android:bundlePreprodRelease
    - name: Save Bundle
      uses: actions/upload-artifact@v4
      with:
        name: PreprodBundle
        path: edifikana/front-end/app-android/build/outputs/**/*.aab

  build-android-prod:
    runs-on: self-hosted
    needs: build-android-staging
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        GOOGLE_SERVICES_PREPROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PREPROD }}
        GOOGLE_SERVICES_PROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PROD }}
      run: |
        echo "$GOOGLE_SERVICES_PREPROD" | base64 -d > edifikana/front-end/app-android/src/preprod/google-services.json
        echo "$GOOGLE_SERVICES_PROD" | base64 -d > edifikana/front-end/app-android/src/prod/google-services.json
    - name: Build Unsigned Bundle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :edifikana:front-end:app-android:bundleProdRelease
    - name: Save Bundle
      uses: actions/upload-artifact@v4
      with:
        name: UnsignedProdBundle
        path: edifikana/front-end/app-android/build/outputs/**/*.aab
    - name: Load Fastlane file
      env:
        FASTLANE_SECRETS: ${{ secrets.EDIFIKANA_FASTLANE_SECRETS }}
      run: echo "$FASTLANE_SECRETS" | base64 -d > edifikana/front-end/app-android/.secrets/silken-physics.json
    - name: Load Android upload signing key
      env:
        UPLOAD_KEY: ${{ secrets.EDIFIKANA_UPLOAD_KEY }}
      run: echo "$UPLOAD_KEY" | base64 -d > edifikana/front-end/app-android/.secrets/upload.jks
    - name: Build Bundle
      env:
        EDIFIKANA_STORE_PASSWORD: ${{ secrets.EDIFIKANA_STORE_PASSWORD }}
        EDIFIKANA_KEY_ALIAS: ${{ secrets.EDIFIKANA_KEY_ALIAS }}
        EDIFIKANA_KEY_PASSWORD: ${{ secrets.EDIFIKANA_KEY_PASSWORD }}
      run: |
        # TODO: Move to use deploy.sh
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        brew install fastlane
        cd edifikana/front-end/app-android
        fastlane run validate_play_store_json_key
        fastlane internal

  build-function-staging:
    runs-on: self-hosted
    environment: edifikana-function-stage
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
        GDRIVE_ACCESS_SERVICE: ${{ secrets.GDRIVE_ACCESS_SERVICE }}
      run: |
        echo "$FIREBASE_ADMIN_SDK" | base64 -d > edifikana/back-end/.secrets/firebase-adminsdk.json
        echo "$GDRIVE_ACCESS_SERVICE" | base64 -d > edifikana/back-end/.secrets/gdrive-access-service.json
    - name: Build Staging
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :edifikana:back-end:buildFunction
    - name: Save Jar
      uses: actions/upload-artifact@v4
      with:
        name: PreprodJar
        path: edifikana/back-end/build/deploy/**/*.jar
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Use gcloud CLI
      run: |
        gcloud functions deploy edifikana-cloud-function \
          --gen2 \
          --entry-point=com.cramsan.edifikana.server.CloudFirebaseApp \
          --runtime=java17 \
          --memory=512MB \
          --region=us-west1 \
          --source=build/deploy \
          --set-env-vars STORAGE_FOLDER_ID=${{ vars.EDIFIKANA_STORAGE_FOLDER_ID }} \
          --set-env-vars TIME_CARD_SPREADSHEET_ID=${{ vars.EDIFIKANA_TIME_CARD_SPREADSHEET_ID }} \
          --set-env-vars EVENT_LOG_SPREADSHEET_ID=${{ vars.EDIFIKANA_EVENT_LOG_SPREADSHEET_ID }} \
          --set-env-vars FORM_ENTRIES_SPREADSHEET_ID=${{ vars.EDIFIKANA_FORM_ENTRIES_SPREADSHEET_ID }} \
          --set-env-vars PROJECT_NAME=${{ vars.EDIFIKANA_PROJECT_NAME }}

  build-function-prod:
    runs-on: self-hosted
    needs: build-function-staging
    environment: edifikana-function-prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
        GDRIVE_ACCESS_SERVICE: ${{ secrets.GDRIVE_ACCESS_SERVICE }}
      run: |
        echo "$FIREBASE_ADMIN_SDK" | base64 -d > edifikana/back-end/.secrets/firebase-adminsdk.json
        echo "$GDRIVE_ACCESS_SERVICE" | base64 -d > edifikana/back-end/.secrets/gdrive-access-service.json
    - name: Build Staging
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :edifikana:back-end:buildFunction
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Use gcloud CLI
      run: gcloud info
