# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish Edifikana

on:
  push:
    branches: [ "cramsan/test_ci" ]

permissions:
  contents: read

env:
  ANDROID_HOME: "/opt/Android/sdk"

jobs:
  build-android-staging:
    runs-on: self-hosted
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        GOOGLE_SERVICES_PREPROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PREPROD }}
        GOOGLE_SERVICES_PROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PROD }}
      run: |
        echo "$GOOGLE_SERVICES_PREPROD" | base64 -d > edifikana/front-end/app-android/src/preprod/google-services.json
        echo "$GOOGLE_SERVICES_PROD" | base64 -d > edifikana/front-end/app-android/src/prod/google-services.json
    - name: Load Fastlane file
      env:
        FASTLANE_SECRETS: ${{ secrets.EDIFIKANA_FASTLANE_SECRETS }}
      run: echo "$FASTLANE_SECRETS" | base64 -d > edifikana/front-end/app-android/.secrets/silken-physics.json
    - name: Load Android upload signing key
      env:
        UPLOAD_KEY: ${{ secrets.EDIFIKANA_UPLOAD_KEY }}
      run: echo "$UPLOAD_KEY" | base64 -d > edifikana/front-end/app-android/upload.jks

  build-android-prod:
    runs-on: self-hosted
    needs: build-android-staging
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Load Firebase service files
      env:
        GOOGLE_SERVICES_PREPROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PREPROD }}
        GOOGLE_SERVICES_PROD: ${{ secrets.EDIFIKANA_GOOGLE_SERVICES_PROD }}
      run: |
        echo "$GOOGLE_SERVICES_PREPROD" | base64 -d > edifikana/front-end/app-android/src/preprod/google-services.json
        echo "$GOOGLE_SERVICES_PROD" | base64 -d > edifikana/front-end/app-android/src/prod/google-services.json
    - name: Load Fastlane file
      env:
        FASTLANE_SECRETS: ${{ secrets.EDIFIKANA_FASTLANE_SECRETS }}
      run: echo "$FASTLANE_SECRETS" | base64 -d > edifikana/front-end/app-android/.secrets/silken-physics.json
    - name: Load Android upload signing key
      env:
        UPLOAD_KEY: ${{ secrets.EDIFIKANA_UPLOAD_KEY }}
      run: echo "$UPLOAD_KEY" | base64 -d > edifikana/front-end/app-android/upload.jks
    - name: Build Bundle
      env:
        EDIFIKANA_STORE_PASSWORD: ${{ secrets.EDIFIKANA_STORE_PASSWORD }}
        EDIFIKANA_KEY_ALIAS: ${{ secrets.EDIFIKANA_KEY_ALIAS }}
        EDIFIKANA_KEY_PASSWORD: ${{ secrets.EDIFIKANA_KEY_PASSWORD }}
      run: |
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        brew install fastlane
        cd edifikana/front-end/app-android
        fastlane run validate_play_store_json_key
        fastlane internal

  build-function-staging:
    runs-on: self-hosted
    needs: build-android-staging
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Publish to Staging
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :edifikana:back-end:release
  build-function-prod:
    runs-on: self-hosted
    needs: build-function-staging
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Publish to Staging
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :edifikana:back-end:release

