name: Update Versions File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  "Refresh-Versions":
    runs-on: "ubuntu-latest"
    steps:
      - id: step-0
        name: check-out
        uses: actions/checkout@v3
        with:
          ref: main
      - id: step-1
        name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - id: step-2
        name: create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: dependency-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: step-3
        name: gradle refreshVersions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions
      - id: step-4
        name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh versions.properties
          new_branch: dependency-update
          push: --force --set-upstream origin dependency-update
      - id: step-5
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: dependency-update
          base: main
          title: Upgrade gradle dependencies
          body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found those library updates!'
          token: ${{ secrets.GITHUB_TOKEN }}
